  robot_base_frame: "base_link"
  origin_z: 0.0
  z_resolution: 1
  z_voxels: 2

  obstacle_range: 2.5
  raytrace_range: 3.0

  publish_voxel_map: true
  transform_tolerance: 0.5
  meter_scoring: true

  footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
  footprint_padding: 0.1

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/map"
    subscribe_to_updates: true
    first_map_only: false

  obstacles_layer:
    observation_sources: laser_scan_sensor
    # laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    laser_scan_sensor: {
      sensor_frame: "laser", 
      data_type: LaserScan, 
      topic: "/scan", 
      marking: true, 
      clearing: true, 
      min_obstacle_height: -0.5, 
      max_obstacle_height: 5.0, 
      obstacle_range: 8.5, 
      raytrace_range: 8.5,
      inf_is_valid: true
    }

  inflater_layer:
    inflation_radius: 0.15